services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=mongodb://db:27017
      - DATABASE_NAME=cross_the_line
    depends_on:
      - db

  db:
    image: "mongo:latest"
    container_name: dangobalango
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:8000
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - network

  healthcheck:
    build:
      context: ./health-check
      dockerfile: Dockerfile
    container_name: healthcheck
    ports:
      - "3001:8080"
    environment:
      - PORT=8080
    networks:
      - network

volumes:
  mongo_data:

networks:
  network:
